### ISSUE TITLE
blackbody graphs.ipynb - Not Loading !!

### ISSUE THREAD

**Issue by Hridoy-31** [Rey-commits/Computational-Physics-Repo#2]
I think there is something wrong in `blackbody graphs.ipynb`. I have run it locally on my machine, and some online jupyter notebook too. But everytime it gives me error like **File Load Error for blackbody graphs.ipynb**  or **Unreadable Notebook** or **error reading JSON**. Can you please fix it ? or provide me a way to get it rendered ?

This is all I have to say. Thanks for this awesome repo. Have a great day !!

**Comment by mesuga-reymond** [comment]
Hey bro thanks for the comments. Please check the file again, i think its working now. Pardon me if you find this repo very unorganized.

**Comment by Hridoy-31** [comment]
Yup, it's working now. Thanks for your quick response !!
